[package]
name = "spair-realworld"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# chrono = { version = "0.4.10", features = ["serde"] }
# dotenv_codegen = "0.15.0"
# lazy_static = "1.4.0"
# log = "0.4.8"
# parking_lot = "0.10.0"
# pulldown-cmark = "0.6.1"
# serde = "1.0.104"
# serde_json = "1.0.44"
thiserror = "1"
# wasm-bindgen = "0.2.63"
# wasm-logger = "0.2.0"
#wee_alloc = "0.4.5"
newtype = "0.2"
spair = { path = "../../spair", features = ["partial-non-keyed-list", "fetch-json"] }
types = { path = "./types" }

# [dependencies.web-sys]
# version = "0.3"
# features = [
#   "Document",
#   "Element",
#   "Node",
#   "Window",
#   "HtmlCollection",
# ]

[dev-dependencies]
js-sys = "0.3.37"
wasm-bindgen-futures = "0.4.10"
wasm-bindgen-test = "0.3.10"
